version: 3.1
services:
  laboratory:
    image: node:iron-alpine3.21
    volumes:
      - ./credentialVerificate:/app
    working_dir: /app
    command: sh -c "npm install @electron/asar && node index.js"